logging:
  level:
    root: INFO
    com.popisna_lista: DEBUG  # Ensure the package name matches your actual Java packages

  file:
    name: ./log/popisna_lista.log  # Adjusted log file name to match your project name

  pattern:
    level: r=%X{r} ip=%X{ip} %5p  # Customize this if needed

spring:
  application:
    name: popisna_lista
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/my_project_inventar_lista_test?allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: myuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  error:
    include-message: always
spring.mvc.format.date: iso
spring.mvc.format.date-time: iso
spring.mvc.format.time: iso